name: Деплой на хостинг

on:
  push:
    branches: [ main ]  # Срабатывает только при пуше в main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка кода
        uses: actions/checkout@3
        
       - name: Деплой по FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /deboart.ru/www/wp-content/themes/tt4-deboart/
          dangerous-clean-slate: false  # НЕ удалять лишние файлы на сервере
