name: Deploy to FTP

on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v3
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /deboart.ru/www/wp-content/themes/tt4-deboart/
        dangerous-clean-slate: false  # НЕ удалять лишние файлы на сервере
